name: input
on: 
  workflow_dispatch:
    inputs:
      Test: 
        description: This is Test input env
        required: true
        default: sri
        type: choice
        options:
           - test
           - dev
           - prod
           - uat

jobs:
    inputvalues:
       runs-on: ubuntu-latest
       steps:
         - name: Deploy the app
           run: echo "Deploy the application to ${{inputs.Test}}"
       
      
 
     
