 name: sequentially running jobs
 on: push
 jobs:
    build:
       runs-on: ubuntu-latest
       steps:
         - name: Build job
           run: echo "This is Build job!!"

    test:
       runs-on: ubuntu-latest
       needs: build
       steps:
         - name: Test Job
           run: echo "This is Test job@@@"

    deploy: 
        runs-on: ubuntu-latest
        needs: test
        steps:
          - name: Deploy job
            run: echo "This is deploy job####"

    prod:
      runs-on: ubuntu-latest
      steps:
         - name: Production job
           run: echo "This is Prod%%"
 
